# TCL File Generated by Component Editor 16.1
# Wed May 05 22:07:33 BRT 2021
# DO NOT MODIFY


# 
# external_handshake_mem "external_handshake_mem" v1.0
# Daniel Gaio 2021.05.05.22:07:33
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module external_handshake_mem
# 
set_module_property DESCRIPTION ""
set_module_property NAME external_handshake_mem
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Daniel Gaio"
set_module_property ICON_PATH ../quartus/
set_module_property DISPLAY_NAME external_handshake_mem
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file top.vhd VHDL PATH ../handshake_memory/top.vhd TOP_LEVEL_FILE
add_fileset_file memory_state_machine.vhd VHDL PATH ../handshake_memory/memory_state_machine.vhd
add_fileset_file memory.vhd VHDL PATH ../handshake_memory/memory.vhd


# 
# parameters
# 
add_parameter DATA_WIDTH NATURAL 8
set_parameter_property DATA_WIDTH DEFAULT_VALUE 8
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH TYPE NATURAL
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""


# 
# connection point read
# 
add_interface read avalon end
set_interface_property read addressUnits WORDS
set_interface_property read associatedClock clock
set_interface_property read associatedReset ""
set_interface_property read bitsPerSymbol 8
set_interface_property read burstOnBurstBoundariesOnly false
set_interface_property read burstcountUnits WORDS
set_interface_property read explicitAddressSpan 0
set_interface_property read holdTime 0
set_interface_property read linewrapBursts false
set_interface_property read maximumPendingReadTransactions 0
set_interface_property read maximumPendingWriteTransactions 0
set_interface_property read readLatency 0
set_interface_property read readWaitTime 1
set_interface_property read setupTime 0
set_interface_property read timingUnits Cycles
set_interface_property read writeWaitTime 0
set_interface_property read ENABLED true
set_interface_property read EXPORT_OF ""
set_interface_property read PORT_NAME_MAP ""
set_interface_property read CMSIS_SVD_VARIABLES ""
set_interface_property read SVD_ADDRESS_GROUP ""
set_interface_assignment read embeddedsw.configuration.isFlash 0
set_interface_assignment read embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment read embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment read embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset ""
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 clk_t beginbursttransfer Input 1
add_interface_port avalon_slave_0 data_out_t writeresponsevalid_n Output data_width
add_interface_port avalon_slave_0 ReqLeit_t beginbursttransfer Input 1
add_interface_port avalon_slave_0 Ack_t_in_sm beginbursttransfer Input 1
add_interface_port avalon_slave_0 Ack_t_out_sm writeresponsevalid_n Output 1
add_interface_port avalon_slave_0 dado_ptr_t writeresponsevalid_n Output 1
add_interface_port avalon_slave_0 reset_t beginbursttransfer Input 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0

